### ISSUE TITLE
3rd table

### ISSUE THREAD

**Issue by nelsaow** [tad-iizuka/CoreDataSample#1]
Great Project! I'm trying to create a new 3rd table, but find out a lot of issues, can you help me? Thanks

**Comment by nelsaow** [comment]
Here is my code https://github.com/nelsaow/CoreDataSample-master-2

**Comment by tad-iizuka** [comment]
Could you tell me What is your problem???

**Comment by nelsaow** [comment]
I'm trying to add one more tableview in your project, and got a lot of issues, can you help me?

**Comment by tad-iizuka** [comment]
Thank you for your reply. I'd like to know what is your issue? You are asking what compile error is?

**Comment by nelsaow** [comment]
thanks for your reply too. your code is perfect. My problem is, I'm trying to add a new table, because your project have two, and I need three tables. I think my compile error is about the entities relationship, I can not figure it out, actually, I'm so new in ios swift. Do you think it's simple to implement a new tableview in your project? Thanks

**Comment by tad-iizuka** [comment]
1. Select all files in Entity -> [delete] -> Move to Trash
2. Select file “CoreDataSample.xcdatamodeld”
3. Remove all numeric in Relationship name in all ENTITIES
    - "serie2" -> "serie"
4. Select Serie ENTITY
    - Codegen(in Right side bar) change to "Manual/None"
5. Select All ENTITIES
6. Editor -> Create NSManagedObject SubClass -> Next ->Next -> Select folder -> Create
7. Product -> Clean

I think error in entity files will disappear. After that, You should modify every codes by the new entity define.

Good luck.

**Comment by nelsaow** [comment]
thanks, really appreciate your help. but unfortunately, I did it and still has compile error. Do you know the way am I using is correct?  I didn't find some articles about this topic on the web. Do you get what I would like to do? Like, add a new tableview with the same relationship, for exemple manager/employee/worklist. thanks

**Comment by tad-iizuka** [comment]
As you know, this is not coreData related issues. As I said, You should modify every codes by the new entity define. Like, "serie2" -> "serie". After that, some error remains which is logical error that you can solve. Good luck.

**Comment by tad-iizuka** [comment]
Check this out. https://github.com/tad-iizuka/CoreDataSample-master-2

**Comment by nelsaow** [comment]
Thanks so much for solving my problem. It's running perfectly.

**Comment by tad-iizuka** [comment]
Don’t mention it.
